print(10 + 3)   [for addition]
print(10 - 3)   [for substraction]
print(10 * 3)   [for multiplication]
print(10 / 3)   [for division in floating]
print(10 // 3)  [for intiger]
print(10 % 3)   [for remainder]
# print(10 ** 3)  [for exponent]